### ISSUE TITLE
Edit Test doesn't work

### ISSUE THREAD

**Issue by PeterNgTr** [codecept-js/ui#19]
<img width="909" alt="Screenshot 2019-11-28 at 15 16 49" src="https://user-images.githubusercontent.com/7845001/69813381-5be95e80-11f2-11ea-8b3c-c4c00bf3aec6.png">

Clicking Edit test on test run page doesn't work.

```sh
Failed to open editor:  Error: Command failed: undefined "/Users/thanhnguyen/Desktop/ui/example/todomvc-tests/create-todos_test.js"
/bin/sh: undefined: command not found

Please, update your settings. Current editor command: undefined
```

**Comment by kaflan** [comment]
@DavertMik  @PeterNgTr  maybe better integrate ace.js? or other code editor js?

**Comment by PeterNgTr** [comment]
@kaflan we could try 👍

**Comment by PeterNgTr** [comment]
```js
const debug = require('debug')('codepress:open-in-editor');
const { exec } = require('child_process');
const { getSettings } = require('./settings-repository');

const openVSCode = fileName => {
    const { editor } = getSettings();
    exec(`${editor} "${fileName}"`, (err) => {
        if (!err) return;
        console.error('Failed to open editor: ', err.toString()); // eslint-disable-line
        console.error(`Please, update your settings. Current editor command: ${editor}`); // eslint-disable-line
        debug(`Failed to open Editor - ${err}`);
    });
};

module.exports = fileName => {
    // TODO Make this configurable
    openVSCode(fileName);
};
```
seems like it open the vscode on the host machine, but we won't be sure that everyone has this editor installed on their machine.

**Comment by PeterNgTr** [comment]
oh, I understood gradually, we should provide the editor cmd in the settings menu, then the edit in editor will execute the code editor by reading the settings.

**Comment by DavertMik** [comment]
> we should provide the editor cmd in the settings menu, then the edit in editor will execute the code editor by reading the settings.

Yes, it is, however, there should be a default value for that...

**Comment by kaflan** [comment]
> @kaflan we could try 👍

yes maybe I can implement simple editor(maybe in vue has a package) in browser @DavertMik  needed or not?

**Comment by PeterNgTr** [comment]
> > @kaflan we could try 👍
> 
> yes maybe I can implement simple editor(maybe in vue has a package) in browser.
> @DavertMik needed or not?

Completely agree to have an embedded editor instead of opening it in the editor cause we don’t really know what editor they use.

**Comment by DavertMik** [comment]
@PeterNgTr I am against the editor because we won't be able to bring experience like in ide. The next problem is to save test into a file... Because test may use variables from that file.

Anyway, I will provide a config option for an editor and ask a user to configure it

**Comment by kaflan** [comment]
<img width="1680" alt="Screenshot 2019-12-04 at 19 20 25" src="https://user-images.githubusercontent.com/3959504/70165208-2d282800-16cb-11ea-921f-11415e8df7ba.png">
@PeterNgTr @DavertMik  I create simple error message, and create this. modal window from
[uri](https://github.com/codecept-js/ui/pull/36)

**Comment by kaflan** [comment]
I tried edded prisma edditor tomorow

**Comment by DavertMik** [comment]
Error message is displayed now
