### ISSUE TITLE
Window size doesnt resize preview test runner window 

### ISSUE THREAD

**Issue by natkrish** [codecept-js/ui#31]
#1 Load Codecept UI on your localhost
#2 Click on settings and change window size of your choice 
#3 try running the test 
Expected: The preview test runner should run the test on the new window size  given as per config 
Actual: The preview test runner still runs on 800x600 

See attached screenshots 
![preview test runner](https://user-images.githubusercontent.com/12541984/70049062-bce2af00-15c3-11ea-9454-f70f7f8efc5e.png)
![settings config](https://user-images.githubusercontent.com/12541984/70049063-bce2af00-15c3-11ea-9aba-47b738262575.png)

**Comment by DavertMik** [comment]
Should be fixed in 0.2.5
