### ISSUE TITLE
ERROR:  {} TypeError: done is not a function     at bootstrap 

### ISSUE THREAD

**Issue by vitaly87** [codecept-js/ui#40]
#### What are you trying to achieve?
I am trying to run codeceptjs with npx codecept-ui
the issue I am getting error with
`
 bootstrap: async function (done) {`

I think the best option to do new things in codeceptjs is to have complex e2e and run eatch new codeceptjs things first on it and then publish...

**Comment by DavertMik** [comment]
> I think the best option to do new things in codeceptjs is to have complex e2e and run eatch new codeceptjs things first on it and then publish...

Sorry, I don't find your advice of this kind to be valuable

**Comment by vitaly87** [comment]
@DavertMik  why you dont agree with me? the new feature should not break the old one this is basic.
If all new feature break the automation that user have this isnt stable... 
example
if you have some bug automation test and you release the ui codeceptjs then it should work with old functionality, same for other features that I saw that weren't working fully.

**Comment by DavertMik** [comment]
Fixed in 0.2.3
Please try
